language:
  - cpp

compiler:
  - gcc

dist: 
  - bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.65-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install -qq g++
  - sudo apt-get install cmake

install:
  - cd IfcPlusPlus
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
